
export const GET_NOTE_LIST = 'GET_NOTE_LIST'
export const GET_NOTE_LIST_REQUEST = 'GET_NOTE_LIST_REQUEST'
export const GET_NOTE_LIST_SUCCESS = 'GET_NOTE_LIST_SUCCESS'
export const GET_NOTE_LIST_FAILURE = 'GET_NOTE_LIST_FAILURE'

export const GET_NOTE_UPDATE_LIST = 'GET_NOTE_UPDATE_LIST'

export const UPDATE_CURRENT_NOTE = 'UPDATE_CURRENT_NOTE'

export const SAVE_NOTE = 'SAVE_NOTE'

export const CHANGE_ACTIVE_NOTE = 'CHANGE_ACTIVE_NOTE'

export const CREATE_NEW_NOTE = 'CREATE_NEW_NOTE'

export const DELETE_NOTE = 'DELETE_NOTE'
