
export const GET_NOTE_LIST = 'GET_NOTE_LIST'
export const GET_NOTE_LIST_REQUEST = 'GET_NOTE_LIST_REQUEST'
export const GET_NOTE_LIST_SUCCESS = 'GET_NOTE_LIST_SUCCESS'
export const GET_NOTE_LIST_FAILURE = 'GET_NOTE_LIST_FAILURE'

export const UPDATE_CURRENT_NOTE = 'UPDATE_CURRENT_NOTE'
