export const CHANGE_ORDER_TYPE = 'CHANGE_ORDER_TYPE'

export const GET_NOTEBOOKS_LIST = 'GET_NOTEBOOKS_LIST'
export const GET_NOTEBOOKS_LIST_REQUEST = 'GET_NOTEBOOKS_LIST_REQUEST'
export const GET_NOTEBOOKS_LIST_SUCCESS = 'GET_NOTEBOOKS_LIST_SUCCESS'
export const GET_NOTEBOOKS_LIST_FAILURE = 'GET_NOTEBOOKS_LIST_FAILURE'

export const DELETE_NOTEBOOK = 'DELETE_NOTEBOOK'
